import { Ctx, drawFlow } from "./helpers.ts";

export async function buildBelehrungPdf(ctx: Ctx): Promise<Uint8Array> {
  await drawFlow(
    ctx,
    "Bördesnack24 – Belehrung nach § 43 IfSG",
    async () => ctx.pdf.addPage([595, 842]),
    [
      { type: "italic-note", text: "Belehrungsbogen für Personen mit Tätigkeit im Lebensmittelbereich · Stand: 21.02.2014" },
      { type: "space" },

      { type: "h2", text: "Belehrung gemäß § 43 Abs. 1 Infektionsschutzgesetz (IfSG)" },
      { type: "h3", text: "Wer muss belehrt werden?" },
      { type: "p", text: "Vor erstmaliger Ausübung einer Tätigkeit im Lebensmittelbereich benötigen eine Belehrung und Bescheinigung gemäß § 43 Abs. 1 Infektionsschutzgesetz durch ihr Gesundheitsamt:" },
      { type: "li", text: "Personen, die gewerbsmäßig folgende Lebensmittel herstellen, behandeln oder in den Verkehr bringen:" },
      { type: "sub-li", text: "Fleisch, Geflügelfleisch und Erzeugnisse daraus," },
      { type: "sub-li", text: "Milch und Erzeugnisse auf Milchbasis," },
      { type: "sub-li", text: "Fische, Krebse oder Weichtiere und Erzeugnisse daraus," },
      { type: "sub-li", text: "Eiprodukte," },
      { type: "sub-li", text: "Säuglings- und Kleinkindernahrung," },
      { type: "sub-li", text: "Speiseeis und Speiseeishalberzeugnisse," },
      { type: "sub-li", text: "Backwaren mit nicht durchgebackener oder durcherhitzter Füllung oder Auflage," },
      { type: "sub-li", text: "Feinkost-, Rohkost- und Kartoffelsalate, Marinaden, Mayonnaisen, andere emulgierte Soßen, Nahrungshefen," },
      { type: "sub-li", text: "Sprossen und Keimlinge zum Rohverzehr sowie Samen zur Herstellung von Sprossen und Keimlingen zum Rohverzehr," },
      { type: "p", text: "und dabei mit ihnen direkt (mit der Hand) oder indirekt (über Bedarfsgegenstände, z. B. Geschirr, Besteck und andere Arbeitsmaterialien) in Berührung kommen, ODER" },
      { type: "li", text: "Personen, die in Küchen von Gaststätten, Restaurants, Kantinen, Cafés oder sonstigen Einrichtungen mit oder zur Gemeinschaftsverpflegung tätig sind." },

      { type: "h3", text: "Warum müssen besondere Vorsichtsmaßnahmen beachtet werden?" },
      { type: "p", text: "In den oben genannten Lebensmitteln können sich Krankheitserreger besonders leicht vermehren. Durch den Verzehr von mit Krankheitserregern verunreinigten Lebensmitteln können Menschen an Lebensmittelinfektionen oder -vergiftungen schwer erkranken. In Gaststätten oder Einrichtungen mit oder zur Gemeinschaftsverpflegung kann davon eine große Anzahl von Menschen betroffen sein." },
      { type: "p", text: "Aus diesem Grund muss von jedem Beschäftigten zum Schutz des Verbrauchers und zum eigenen Schutz ein hohes Maß an Eigenverantwortung und Beachtung von Hygieneregeln verlangt werden." },
      { type: "italic-note", text: "(Die wichtigsten Regeln wurden in dem Merkblatt „Hygieneregeln in der Gemeinschaftsgastronomie\" vom Bundesinstitut für Risikobewertung zusammengestellt: www.bfr.bund.de › Publikationen › Merkblätter › Merkblätter für weitere Berufsgruppen)." },

      { type: "h3", text: "Wann dürfen die oben genannten Tätigkeiten nicht ausgeübt werden?" },
      { type: "li", text: "Wenn bei Ihnen Krankheitszeichen (Symptome) auftreten, die auf eine der folgenden Krankheiten hinweisen oder die ein Arzt bei Ihnen festgestellt hat, dürfen Sie gemäß Infektionsschutzgesetz nicht in diesem Bereich tätig sein oder beschäftigt werden:" },
      { type: "sub-li", text: "Akute infektiöse Gastroenteritis (plötzlich auftretender, ansteckender Durchfall), ausgelöst durch Salmonellen, Shigellen, Campylobacter, Rotaviren, Noroviren oder andere Durchfallerreger," },
      { type: "sub-li", text: "Cholera," },
      { type: "sub-li", text: "Typhus oder Paratyphus," },
      { type: "sub-li", text: "Hepatitis A oder E (Leberentzündung)," },
      { type: "sub-li", text: "Infizierte Wunden oder Hautkrankheiten, bei denen die Möglichkeit besteht, dass deren Krankheitserreger über Lebensmittel auf andere Menschen übertragen werden können." },
      { type: "li", text: "Wenn die Untersuchung einer Stuhlprobe von Ihnen den Nachweis eines der folgenden Krankheitserreger ergeben hat:" },
      { type: "sub-li", text: "Salmonellen," },
      { type: "sub-li", text: "Shigellen," },
      { type: "sub-li", text: "enterohämorrhagische Escherichia-coli-Bakterien (EHEC)," },
      { type: "sub-li", text: "Cholerabakterien," },
      { type: "p", text: "besteht ein Tätigkeitsverbot oder Beschäftigungsverbot im Lebensmittelbereich. Das Tätigkeits- oder Beschäftigungsverbot besteht auch, wenn Sie diese Erreger ausscheiden, ohne dass Sie Krankheitszeichen (s. u.) aufweisen." },
      { type: "h3", text: "Hinweis:" },
      { type: "p", text: "Das Gesundheitsamt kann Ausnahmen von den Verboten nach dieser Vorschrift zulassen, wenn Maßnahmen durchgeführt werden, mit denen eine Übertragung der aufgeführten Krankheiten und Krankheitserreger verhütet werden kann." },

      { type: "h3", text: "Folgende Krankheitszeichen weisen auf die genannten Krankheiten hin:" },
      { type: "li", text: "Durchfall (mindestens 3 ungeformte Stühle in 24 Stunden)," },
      { type: "li", text: "Übelkeit, Erbrechen oder Bauchschmerzen," },
      { type: "li", text: "Fieber (Körpertemperatur >= 38,5 °C)," },
      { type: "li", text: "Gelbfärbung der Haut und der Augäpfel," },
      { type: "li", text: "Wunden oder offene Stellen von Hauterkrankungen, wenn sie gerötet, schmierig belegt, nässend oder geschwollen sind." },

      { type: "h3", text: "Wer muss informiert werden?" },
      { type: "p", text: "Wenn bei Ihnen eines oder mehrere der genannten Krankheitszeichen auftreten, nehmen Sie unbedingt den Rat Ihres Haus- oder Betriebsarztes in Anspruch. Sagen Sie ihm auch, dass Sie in einem Lebensmittelbetrieb arbeiten. Außerdem sind Sie verpflichtet, unverzüglich Ihren Vorgesetzten über die Erkrankung zu informieren." },

      { type: "h3", text: "Hinweise auf Anlage I und Anlage II" },
      { type: "p", text: "Wir bitten Sie, die nachfolgende Erklärung zu unterschreiben, dass Sie mündlich sowie schriftlich auf die Tätigkeitsverbote gemäß Infektionsschutzgesetz hingewiesen worden sind und die Belehrung verstanden haben und dass bei Ihnen keine Tatsachen für ein Tätigkeitsverbot bekannt sind (Anlage I)." },
      { type: "p", text: "Nach der Belehrung in mündlicher und schriftlicher Form erhalten Sie die Bescheinigung für Ihren Arbeitgeber oder Dienstherren (Anlage II)." },

      { type: "h2", text: "Besondere Hinweise für Arbeitgeber/Dienstherren" },
      { type: "li", text: "Auch Arbeitgeber haben die in Anlage I niedergelegte Erklärung abzugeben, sofern sie zu dem auf Seite 1 des Merkblattes ausgeführten Personenkreis gehören." },
      { type: "li", text: "Sie dürfen die auf Seite 1 des Merkblattes beschriebenen Tätigkeiten nur ausüben, wenn Sie eine Bescheinigung gemäß Anlage II erhalten haben oder im Besitz eines Gesundheitszeugnisses gemäß § 18 Bundesseuchengesetz sind." },
      { type: "li", text: "Bei erstmaliger Ausübung der Tätigkeit darf die Bescheinigung des Gesundheitsamtes nicht älter als drei Monate sein." },
      { type: "li", text: "Sie haben Personen, die die auf Seite 1 des Merkblattes genannten Tätigkeiten ausüben, nach Aufnahme ihrer Tätigkeit und im weiteren alle zwei Jahre über die auf Seite 2 aufgeführten Bestimmungen des Infektionsschutzgesetzes zu belehren und die Teilnahme an der Belehrung zu dokumentieren." },
      { type: "li", text: "Sie haben Ihre eigene Bescheinigung und die Ihrer Beschäftigten, sowie die Dokumentation über die letzte Belehrung an der Arbeitsstätte verfügbar zu halten und den Mitarbeitern der zuständigen Behörde alle genannten Bescheinigungen auf Verlangen vorzulegen. Bei Tätigkeiten an wechselnden Standorten genügt die Vorlage einer beglaubigten Kopie." },
      { type: "li", text: "Haben Sie selbst oder einer Ihrer Beschäftigten eine der auf Seite 2 dieses Merkblattes genannten Krankheitszeichen (Symptome), ist eine der dort genannten Krankheiten oder die Ausscheidung einer der aufgezählten Krankheitserreger ärztlich festgestellt worden, so müssen Sie Hygienemaßnahmen ergreifen, die geeignet sind, eine Weiterverbreitung der Krankheitserreger an der Arbeitsstätte zu verhindern. Auskunft hierzu erteilt die zuständige Behörde für Lebensmittelüberwachung und Ihr Gesundheitsamt." },
      { type: "li", text: "Diese Belehrung ersetzt nicht die regelmäßige Belehrung nach der Lebensmittelhygiene-Verordnung." },

      { type: "h2", text: "Weitere Informationen zu den Krankheiten und Hygienemaßnahmen finden Sie auf folgenden Webseiten:" },
      { type: "h3", text: "Robert Koch-Institut" },
      { type: "p", text: "www.rki.de › Infektionskrankheiten A–Z" },
      { type: "h3", text: "Bundeszentrale für gesundheitliche Aufklärung" },
      { type: "p", text: "www.infektionsschutz.de" },
      { type: "h3", text: "Bundesinstitut für Risikobewertung" },
      { type: "p", text: "www.bfr.bund.de › Publikationen › Merkblätter › Merkblätter für weitere Berufsgruppen" },

      { type: "h2", text: "Anlage I – Erklärung gemäß § 43 Abs. 1 Nr. 2 Infektionsschutzgesetz" },
      { type: "placeholder", label: "Frau/Herr", value: "[Vorname Name]" },
      { type: "placeholder", label: "geboren am", value: "[TT.MM.JJJJ]" },
      { type: "placeholder", label: "Straße / Hausnummer", value: "[Straße Nr.]" },
      { type: "placeholder", label: "Postleitzahl / Ort", value: "[PLZ Ort]" },
      { type: "space" },
      { type: "p", text: "Ich erkläre hiermit, dass ich gemäß § 43 Abs. 1 Infektionsschutzgesetz mündlich und schriftlich aufgeklärt wurde und dass bei mir keine Tatsachen für ein Tätigkeitsverbot bekannt sind." },
      { type: "placeholder", label: "Ort, Datum", value: "[Ort, TT.MM.JJJJ]" },
      { type: "placeholder", label: "Unterschrift", value: "[Unterschrift Mitarbeiter/in]" },

      { type: "h2", text: "Anlage II – Bescheinigung des Gesundheitsamtes gemäß § 43 Abs. 1 Nr. 1 Infektionsschutzgesetz" },
      { type: "p", text: "Hiermit wird bescheinigt, dass Frau/Herr" },
      { type: "placeholder", label: "Vorname, Name", value: "[Vorname Name]" },
      { type: "placeholder", label: "am", value: "[TT.MM.JJJJ]" },
      { type: "p", text: "mündlich und schriftlich über die in § 42 Abs. 1 Infektionsschutzgesetz genannten Tätigkeits- und Beschäftigungsverbote und die Verpflichtungen gemäß § 43 Absätze 2, 4 und 5 belehrt worden ist." },
      { type: "placeholder", label: "Gesundheitsamt", value: "[Behörde / Stempel]" },
      { type: "placeholder", label: "Ort, Datum", value: "[Ort, TT.MM.JJJJ]" },
      { type: "placeholder", label: "Unterschrift", value: "[Unterschrift Sachbearbeiter/in]" },
      { type: "italic-note", text: "Hinweis: Diese Bescheinigung darf an Ihrem ersten Arbeitstag nicht älter als drei Monate sein. Bitte geben Sie diese Bescheinigung spätestens dann bei Ihrer Arbeitsstelle ab." },
    ],
    { showLegend: true },
  );
  return await ctx.pdf.save();
}

