insert into public.ki_register (
  key, bezeichnung, system, rolle, zweck, datenkategorien, personenbezug,
  profiling, ist_ki_system, ai_act_kategorie, dsgvo_risiko, rechtsgrundlage,
  kennzeichnung_noetig, kennzeichnung_umgesetzt, freigabe_noetig,
  minderjaehrige, ampel, begruendung, geprueft_am, geprueft_von
) values
('generate_personal_offer','Individuelles Angebot aus der Kaufhistorie','regelbasiert (SQL)','keine',
 'Rabatt auf das in 90 Tagen meistgekaufte Produkt',
 array['kaufhistorie_produkt','kaufhistorie_menge','kaufzeitpunkt'], true,
 true, false, 'kein_ki_system', 'mittel', 'Art. 6 Abs. 1 lit. f DSGVO',
 false, true, false, true, 'gruen',
 'Profiling nach Art. 4 Nr. 4 DSGVO — die Kaufhistorie wird ausgewertet. Kein KI-System: order by sum(quantity), kein Lernen. Art. 22 greift nicht, weil der Rabattsatz mit 10 % fest verdrahtet und für alle gleich ist; es entscheidet sich nur, WELCHES Produkt vergünstigt wird. Kein Ausschluss, keine individuelle Preisbildung. Kennzeichnung freiwillig umgesetzt.',
 date '2026-08-09','Philipp Blume'),
('generate_daily_offers','Tagesangebot nach Wetterlage','regelbasiert (SQL)','keine',
 'Produktauswahl nach Wettervorhersage am Automatenstandort',
 array['wetterdaten_standort_automat'], false,
 false, false, 'kein_ki_system', 'niedrig', 'Art. 6 Abs. 1 lit. f DSGVO',
 false, true, false, false, 'gruen',
 'Kein Personenbezug: Das Angebot ist für alle Kunden identisch. Grundlage ist die DWD-Vorhersage für den Automatenstandort, nicht der Standort des Nutzers. Kein Profiling, kein KI-System.',
 date '2026-08-09','Philipp Blume'),
('generate_weekly_offers','Wochenangebot nach Mindesthaltbarkeitsdatum','regelbasiert (SQL)','keine',
 'Abverkauf kurz vor Ablauf, Vermeidung von Lebensmittelverschwendung',
 array['mhd_bestand'], false,
 false, false, 'kein_ki_system', 'niedrig', 'Art. 6 Abs. 1 lit. f DSGVO',
 false, true, false, false, 'gruen',
 'Reine Bestandslogik ohne jeden Personenbezug. Für alle Kunden gleich.',
 date '2026-08-09','Philipp Blume'),
('grant_birthday_offer','Geburtstagsgutschein','regelbasiert (SQL)','keine',
 'Einmal jährlich ein Gutschein am Geburtstag',
 array['geburtsdatum'], true,
 false, false, 'kein_ki_system', 'mittel', 'Art. 6 Abs. 1 lit. f DSGVO',
 false, false, false, true, 'gelb',
 'GELB, weil zwei Dinge offen sind. Erstens: Das Geburtsdatum ist ein personenbezogenes Merkmal, das die KI-Info-Seite bislang NICHT als Datenquelle nennt — die Transparenzangabe ist insoweit unvollständig. Zweitens: Minderjährige sind betroffen, und ein Kaufanreiz zum Geburtstag braucht eine bewusste Entscheidung darüber, ob er für sie gelten soll. Datumsvergleich, kein KI-System. Freigabe durch Philipp Blume erforderlich.',
 date '2026-08-09','Philipp Blume'),
('customer_chatbot','Automatischer Chat-Assistent','regelbasiert (statisches FAQ)','keine',
 'Beantwortung häufiger Fragen im Kundenbereich',
 array['keine'], false,
 false, false, 'kein_ki_system', 'niedrig', 'Art. 6 Abs. 1 lit. b DSGVO',
 false, true, false, true, 'gruen',
 'Statische Antworten aus einer Konstante, nachgeprüft: kein einziger Netzwerkaufruf in der Datei, kein Modell. Kein KI-System, daher keine Pflicht aus Art. 50 Abs. 1. Die Beschriftung "Automatischer Chat-Assistent" statt "KI" ist deshalb die zutreffende — sie vermeidet zugleich eine unzutreffende KI-Behauptung nach § 5 UWG.',
 date '2026-08-09','Philipp Blume')
on conflict (key) do nothing;
